from snakemake.utils import min_version
min_version("6.0")


import pandas as pd
meta = pd.read_csv('config/meta.csv')
sn_samples = meta[~meta['Batch sn'].isnull()]['Sample id'].values.astype('U')
vs_samples = meta[~meta['Batch vs'].isnull()]['Sample id'].values.astype('U')
ctypes = pd.read_csv('config/markers.csv')['cell_type'].unique().astype('U')


configfile: "config/config.yaml"
container: "workflow/envs/env.sif"

# Load rules
rule all:
    input: expand("results/integrate/cell_states/{ctype}.pdf", ctype=ctypes)
#expand('data/prc/vs/{vs_sample}/progeny.csv', vs_sample=vs_samples)
#expand("data/prc/ctypes/{ctype}_deg.csv", ctype=ctypes)
#'data/prc/niches_mofa.hdf5' #'data/prc/sn_annotated.h5ad'
#expand("data/prc/vs/{vs_sample}/ctlr_scores.csv", vs_sample=vs_samples)
#expand("data/prc/sn/{sn_sample}/adata.h5ad", sn_sample=sn_samples)
#expand("results/integrate/vs_{vs_sample}_mofa.pdf", vs_sample=vs_samples)
#expand("results/integrate/states_{ctype}.pdf", ctype=ctypes)
#expand("results/integrate/ctypes/{ctype}.pdf", ctype=ctypes)
#expand("data/prc/vs/{vs_sample}/lr_scores.csv", vs_sample=vs_samples)
#data/prc/vs/{vs_sample}/hallmarks.csv
#data/prc/vs/{vs_sample}/misty_metrics.csv

#include: "rules/backrm.smk"
include: "rules/qc.smk"
include: "rules/integrate.smk"
include: "rules/atlases.smk"
#include: "rules/deconv.smk"
include: "rules/func.smk"
include: "rules/figures.smk"
include: "rules/mofacell.smk"

# snakemake --profile config/slurm/
