samples: 'config/meta.csv'

cellbender:
    model: full
    expected_cells: 8000
    total_droplets_included: 100000
    fpr: 0.01
    epochs: 150
    posterior_batch_size: 5
    cells_posterior_reg_calc: 50   

qc:
    min_genes: 200
    min_cells: 3
    mt_thr: 5
    ct_thr: 0.99
    db_thr: 0.1

sn_integrate:
    n_hvg: 4096

annotate:
    markers: 'config/markers.csv'
    resolution: 0.25
    annotation: '0:OL;1:OL;2:AS;3:MG;4:OL;5:NEU;6:OPC;7:EC;8:NEU;9:NEU;10:TC;11:OL;12:AS;13:SC;14:BC'

atlases:
    absinta_2021:
        annot: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE180759&format=file&file=GSE180759%5Fannotation%2Etxt%2Egz'
        count: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE180759&format=file&file=GSE180759%5Fexpression%5Fmatrix%2Ecsv%2Egz'
